// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cars.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteCarById = `-- name: DeleteCarById :exec
DELETE FROM cars
WHERE id = $1
`

func (q *Queries) DeleteCarById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCarById, id)
	return err
}
