// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cars.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCar = `-- name: CreateCar :one
INSERT INTO cars ( id, created_at, updated_at, reg_num, mark, model, year, owner_name, owner_surname, owner_patronymic )
VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateCarParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	RegNum          string
	Mark            string
	Model           string
	Year            int32
	OwnerName       string
	OwnerSurname    string
	OwnerPatronymic sql.NullString
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createCar,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RegNum,
		arg.Mark,
		arg.Model,
		arg.Year,
		arg.OwnerName,
		arg.OwnerSurname,
		arg.OwnerPatronymic,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCarById = `-- name: DeleteCarById :exec
DELETE FROM cars
WHERE id = $1
`

func (q *Queries) DeleteCarById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCarById, id)
	return err
}

const getCars = `-- name: GetCars :many
SELECT id, created_at, updated_at, reg_num, mark, model, year, owner_name, owner_surname, owner_patronymic
FROM cars
WHERE
    (reg_num = $1 OR $1 = '') AND
    (mark = $2 OR $2 = '') AND
    (model = $3 OR $3 = '') AND
    (year = $4 OR $4 = 0) AND
    (owner_name = $5 OR $5 = '') AND
    (owner_surname = $6 OR $6 = '') AND
    (owner_patronymic = $7 OR $7 IS NULL )
LIMIT CASE WHEN $8 = -1 THEN NULL ELSE $8 END
OFFSET ($9 - 1) * $8
`

type GetCarsParams struct {
	RegNum          string
	Mark            string
	Model           string
	Year            int32
	OwnerName       string
	OwnerSurname    string
	OwnerPatronymic sql.NullString
	Column8         interface{}
	Column9         interface{}
}

func (q *Queries) GetCars(ctx context.Context, arg GetCarsParams) ([]Car, error) {
	rows, err := q.db.QueryContext(ctx, getCars,
		arg.RegNum,
		arg.Mark,
		arg.Model,
		arg.Year,
		arg.OwnerName,
		arg.OwnerSurname,
		arg.OwnerPatronymic,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegNum,
			&i.Mark,
			&i.Model,
			&i.Year,
			&i.OwnerName,
			&i.OwnerSurname,
			&i.OwnerPatronymic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarkById = `-- name: UpdateMarkById :exec
UPDATE cars
SET mark = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateMarkByIdParams struct {
	ID   uuid.UUID
	Mark string
}

func (q *Queries) UpdateMarkById(ctx context.Context, arg UpdateMarkByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkById, arg.ID, arg.Mark)
	return err
}

const updateModelById = `-- name: UpdateModelById :exec
UPDATE cars
SET model = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateModelByIdParams struct {
	ID    uuid.UUID
	Model string
}

func (q *Queries) UpdateModelById(ctx context.Context, arg UpdateModelByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateModelById, arg.ID, arg.Model)
	return err
}

const updateOwnerNameById = `-- name: UpdateOwnerNameById :exec
UPDATE cars
SET owner_name = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOwnerNameByIdParams struct {
	ID        uuid.UUID
	OwnerName string
}

func (q *Queries) UpdateOwnerNameById(ctx context.Context, arg UpdateOwnerNameByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerNameById, arg.ID, arg.OwnerName)
	return err
}

const updateOwnerPatronymicById = `-- name: UpdateOwnerPatronymicById :exec
UPDATE cars
SET owner_patronymic = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOwnerPatronymicByIdParams struct {
	ID              uuid.UUID
	OwnerPatronymic sql.NullString
}

func (q *Queries) UpdateOwnerPatronymicById(ctx context.Context, arg UpdateOwnerPatronymicByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerPatronymicById, arg.ID, arg.OwnerPatronymic)
	return err
}

const updateOwnerSurnameById = `-- name: UpdateOwnerSurnameById :exec
UPDATE cars
SET owner_surname = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOwnerSurnameByIdParams struct {
	ID           uuid.UUID
	OwnerSurname string
}

func (q *Queries) UpdateOwnerSurnameById(ctx context.Context, arg UpdateOwnerSurnameByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerSurnameById, arg.ID, arg.OwnerSurname)
	return err
}

const updateRegNumById = `-- name: UpdateRegNumById :exec
UPDATE cars
SET reg_num = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateRegNumByIdParams struct {
	ID     uuid.UUID
	RegNum string
}

func (q *Queries) UpdateRegNumById(ctx context.Context, arg UpdateRegNumByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateRegNumById, arg.ID, arg.RegNum)
	return err
}

const updateYearById = `-- name: UpdateYearById :exec
UPDATE cars
SET year = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateYearByIdParams struct {
	ID   uuid.UUID
	Year int32
}

func (q *Queries) UpdateYearById(ctx context.Context, arg UpdateYearByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateYearById, arg.ID, arg.Year)
	return err
}
